backend/CustomUser/urls.py
from django.urls import path
from .views import *

app_name='CustomUser'
urlpatterns = [
    path('confirm-mail/',EmailVerification.as_view(),name="verify email"),
    path('dashboard/',Dashboard.as_view(),name="dashboard"),
    path('',Home.as_view(),name="home_page"),
    path('login/',LoginView.as_view(),name="admin_login"),
    path('map/view/',MapView.as_view(),name="map_view"),
    path('user/logout/',LogoutView.as_view(),name="logout_user"),
    path('donation/all/',DonateListView.as_view(),name="donate_list"),
    path('make/donation/<int:id>/',DonateCompleteView.as_view(),name="make_donation"),
    path('event/list/',EventView.as_view(),name="event_list"),
    path('tree/view/',TreeMapView.as_view(),name="tree_view"),
    path('report/',ReportGeneration.as_view(),name="report"),
    path('downloadcsv/',DownloadCSV.as_view(),name="download"),
    path('profiling/',ProfilingData.as_view(),name="profiling")
]

backend/api/urls.py
from ninja import NinjaAPI
from .views import router as user_router

app = NinjaAPI()

app.add_router('/users/',user_router)

backend/core/urls.py
from django.contrib import admin
from django.urls import path,include
from api.urls import app
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',app.urls),
    path('',include('CustomUser.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/CustomUser/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import UserManager,AbstractBaseUser,PermissionsMixin
from django.utils import timezone
from django.core.validators import RegexValidator
from django.core.mail import send_mail
import uuid
from datetime import timedelta

class CustomUserManager(UserManager):

    def _create_user(self,email,password,**extra_fields):
        if email is None:
            raise ValueError("Email field is empty")
        email=self.normalize_email(email=email)
        user=self.model(email=email,**extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff",False)
        extra_fields.setdefault("is_superuser",False)
        return self._create_user(email,password,**extra_fields)
    def create_superuser(self,email:str|None=...,password:str|None=...,**extra_fields:Any):
        extra_fields.setdefault("is_staff",True)
        extra_fields.setdefault("is_superuser",True)
        extra_fields.setdefault("is_active",True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        if extra_fields.get("is_active") is not True:
            raise ValueError("Superuser must be active")
        return self._create_user(email,password,**extra_fields)
    
class User(AbstractBaseUser,PermissionsMixin):
    phone_number_regex=RegexValidator(
        regex=r'^(\+977)?\d{9,10}$',
        message="Phone number must be entered in the format: '+977'. Up to 10 digits allowed."
    )

    email=models.EmailField(blank=False,unique=True,null=False)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    phone_number=models.CharField(validators=[phone_number_regex],max_length=14,blank=True)
    address=models.CharField(max_length=100,blank=True)
    age=models.IntegerField(default=0)
    is_active=models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)

    date_joined=models.DateTimeField(default=timezone.now)
    last_login=models.DateTimeField(blank=True,null=True)

    objects=CustomUserManager()

    USERNAME_FIELD='email'
    EMAIL_FIELD='email'
    REQUIRED_FIELDS=['password']

    class Meta:
        verbose_name='user'
        verbose_name_plural='users'

    def get_full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self) -> str:
        return f"{self.first_name}"
    
    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

class EmailConfirm(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_valid = models.DateTimeField(default=timezone.now() + timedelta(minutes=30))

    def __str__(self):
        return str(self.user.get_full_name())
    class Meta:
        verbose_name='Email Verification'
        verbose_name_plural='Email Verifications'

class UserPoint(models.Model):
    point=models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.email} point:{self.point}'
    
class TreePlantation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    longitude = models.DecimalField(max_digits=9, decimal_places=6,blank=True,null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6,blank=True,null=True)
    planted=models.BooleanField(default=False)
    def __str__(self):
        return f"Planted by:{self.user.get_full_name()} status:{self.planted}"

backend/event/models.py
from django.db import models
from CustomUser.models import User

class Event(models.Model):
    title=models.CharField(max_length=255)
    image = models.ImageField(upload_to='event_images')
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    signed_users = models.ManyToManyField(User,blank=True)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.title

backend/CustomUser/forms.py
from django import forms
from .models import TreePlantation
from django.forms import ModelForm

class LoginForm(forms.Form):
   email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class DonationForm(ModelForm):
    PLANTED_CHOICES = [
        (True, 'Yes'),
        (False, 'No'),
    ]

    planted = forms.ChoiceField(
        choices=PLANTED_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = TreePlantation
        fields = ('longitude', 'latitude', 'planted')
        widgets = {
            'longitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'latitude': forms.NumberInput(attrs={'class': 'form-control'}),
        }

backend/CustomUser/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse
from django.views import View
from django.views.generic import TemplateView
from .models import User,EmailConfirm,UserPoint,TreePlantation
from django.utils import timezone
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import os
import folium
from .forms import LoginForm,DonationForm
from django.contrib.auth import authenticate,login,logout
from complain.models import UserComplain
from django.template.loader import render_to_string
import branca
from django.contrib.auth.mixins import LoginRequiredMixin
from event.models import Event
from django.utils import timezone
import csv
from django.conf import settings
from ydata_profiling import ProfileReport
import pandas as pd

class Home(View):
    def get(self,request):
        return render(request,"CustomUser/landing_page.html")
    
class EmailVerification(View):

    def get(self,request):
        token=request.GET.get('token')
        email=get_object_or_404(EmailConfirm,id=token)
        if email.time_valid>timezone.now():
            user=get_object_or_404(User,id=email.user.id)
            user.is_active=True
            user.save()
            verification=True
        else:
            verification=False
        context={
            "verified":verification
        }
        return render(request,"CustomUser/email_verification.html",context=context)
    def post(self,request):
        try:
            token=request.GET.get('token')
            email=get_object_or_404(EmailConfirm,id=token)
            user=get_object_or_404(User,id=email.user.id)
            email_confim=EmailConfirm(user=user)
            email.delete()
            email_confim.save()
            backend_link=os.environ.get('PUBLIC_URL')
            confirm_link=f'{backend_link}/confirm-mail/?token={email_confim.id}'
            context={
                "link":confirm_link
            }
            html_message=render_to_string("CustomUser/email_send.html",context=context)
            plain_message=strip_tags(html_message)
            message=EmailMultiAlternatives(
                subject="WasteWatch Email Confirmation!!",
                body=plain_message,
                from_email=settings.EMAIL_HOST_USER,
                to=[user.email]
            )
            message.attach_alternative(html_message,'text/html')
            message.send()
            sucessful=True
        except:
            sucessful=False
        return render(request,"CustomUser/email_resend.html",context={"sucess":sucessful})
    
class LoginView(View):
    def get(self,request):
        return render(request,'CustomUser/login.html',{'form':LoginForm()})
    def post(self,request):
        loginVal=LoginForm(request.POST)
        if loginVal.is_valid():
            email=loginVal.cleaned_data['email']
            password=loginVal.cleaned_data['password']
            getUser=authenticate(email=email,password=password)
            if getUser is not None:
                if getUser.is_superuser:
                    login(request,getUser)
                    return redirect('CustomUser:dashboard')
                else:
                    loginVal.add_error(None,'Only superuser can login')
                    return render(request,'CustomUser/login.html',{'form':loginVal})
        loginVal.add_error(None,'Error Email or password')
        return render(request,'CustomUser/login.html',{'form':loginVal})
class Dashboard(LoginRequiredMixin,View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:admin_login')
        return super().dispatch(request, *args, **kwargs)
    def get(self,request):
        total_user=User.objects.all().count()
        complain_solved=UserComplain.objects.filter(solved=True).count()
        complain_unsolved=UserComplain.objects.filter(solved=False).count()
        event_previous=Event.objects.filter(start_date__lt=timezone.now()).count()
        event_upcoming=Event.objects.filter(start_date__gt=timezone.now()).count()
        tree_count=TreePlantation.objects.filter(planted=True).count()
        context={
            "dashboard":True,
            "userreg":total_user,
            "complain_solved":complain_solved,
            "complain_unsolved":complain_unsolved,
            "event_previous":event_previous,
            "event_upcoming":event_upcoming,
            "tree_count":tree_count,

        }
        return render(request,'CustomUser/dashboard.html',context)
class EventView(LoginRequiredMixin,View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:admin_login')
        return super().dispatch(request, *args, **kwargs)
    def get(self,request):
        event=Event.objects.filter(start_date__gt=timezone.now())
        return render(request,'CustomUser/event.html',context={"event":True,"events":event})   
     
def make_markers_and_add_to_map(map, complain):
    backend_url=os.environ.get("PUBLIC_URL")
    html_code = render_to_string('CustomUser/popover.html',context={"c":complain,"b_url":backend_url})
    iframe = branca.element.IFrame(html=html_code,width="300px",height="400px")
    popup = folium.Popup(iframe,max_width="300px")
    folium.Marker(
            location = [complain.latitude, complain.longitude],
            popup = popup,
            tooltip = complain,
            icon = folium.Icon(icon='fa-trash', prefix='fa')
        ).add_to(map)
    
class MapView(LoginRequiredMixin,TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:admin_login')
        return super().dispatch(request, *args, **kwargs)
    
    template_name = 'CustomUser/map.html'    

    def get_context_data(self, **kwargs):
        figure = folium.Figure()
        map = folium.Map(
            location = [27.680677, 85.326492],
            zoom_start = 14,
            tiles = 'OpenStreetMap')

        map.add_to(figure)
        
        for complain in UserComplain.objects.filter(solved=False):
            make_markers_and_add_to_map(map, complain)
        
        figure.render()
        return {"map": figure}
    
def make_tree_markers_and_add_to_map(map, tree):
    folium.Marker(
            location = [tree.latitude, tree.longitude],
            popup = f"Tree donated by:{tree.user.get_full_name()}",
            tooltip = f"Tree location:{tree.latitude, tree.longitude}",
            icon = folium.Icon(icon='fa-tree', prefix='fa')
        ).add_to(map)
    
class TreeMapView(LoginRequiredMixin,TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:admin_login')
        return super().dispatch(request, *args, **kwargs)
    
    template_name = 'CustomUser/tree_map.html'    

    def get_context_data(self, **kwargs):
        figure = folium.Figure()
        map = folium.Map(
            location = [27.680677, 85.326492],
            zoom_start = 14,
            tiles = 'OpenStreetMap')

        map.add_to(figure)
        
        for tree in TreePlantation.objects.filter(planted=True):
            make_tree_markers_and_add_to_map(map, tree)
        
        figure.render()
        return {"map": figure}
    
class LogoutView(LoginRequiredMixin,View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:login')
        return super().dispatch(request, *args, **kwargs)
    def get(self,request):
        logout(request)
        return redirect('CustomUser:home_page')
    
class DonateListView(LoginRequiredMixin,View):
    def get(self,request):
        donations=TreePlantation.objects.filter(planted=False)
        return render(request,"CustomUser/donation_pending_list.html",context={'donations':donations,"treedonation":True})
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:login')
        return super().dispatch(request, *args, **kwargs)
    
class DonateCompleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        return render(request, "CustomUser/make_donation.html", context={'form': DonationForm, 'id': id,"treedonation":True})

    def post(self, request, id):
        donation = get_object_or_404(TreePlantation, pk=id)
        print(donation.user.email)
        donate_form = DonationForm(request.POST, instance=donation)
        if donate_form.is_valid():
            donate_form.save()
            plain_message = "Your donation Tree has been planted."
            message = EmailMultiAlternatives(
            subject="WasteWatch Nepal Tree Sucessful Donation!",
            body=plain_message,
            from_email=settings.EMAIL_HOST_USER,
            to=[donation.user.email]
            )
            message.send()
            return redirect("CustomUser:donate_list")
        return render(request, "CustomUser/make_donation.html", context={'form': donate_form,'id': id,"treedonation":True})
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:login')
        return super().dispatch(request, *args, **kwargs)

class ReportGeneration(LoginRequiredMixin,View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('CustomUser:login')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self,request):
        fields = ['complain_user__age', 'complain_user__address', 'latitude', 'longitude', 'image', 'description', 'date_of_complain', 'solved_date', 'validated_by__name']

backend/CustomUser/templates/CustomUser/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
  <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
  {% block head %}{% endblock %}
</head>

<body>
  <div class="side-navbar active-nav d-flex justify-content-between flex-wrap flex-column" id="sidebar">
    <ul class="nav flex-column text-white w-100">
      <a href="#" class="nav-link h3 text-white my-2">
        WasteWatch </br>Nepal
      </a>
      <li class="nav-link">
        <i class="bx bxs-dashboard"></i>
        <span class="mx-2"><a href="{% url 'CustomUser:dashboard' %}" {% if dashboard %} class="text-decoration-underline" {% endif %}>Dashboard</a></span>
      </li>
      <li class="nav-link">
        <i class='bx bx-user'></i>
        <span class="mx-2"><a href="/admin" {% if admin %} class="text-decoration-underline"  {% endif %}>Admin</a></span>
      </li>
      <li class="nav-link">
        <i class='bx bx-map'></i>
        <span class="mx-2"><a href="{% url 'CustomUser:map_view' %}">Map</a></span>
      </li>
      <li class="nav-link">
        <i class='bx bx-donate-heart' ></i>
        <span class="mx-2"><a href="{% url 'CustomUser:donate_list' %}" {% if treedonation %} class="text-decoration-underline"  {% endif %}>Donation</a></span>
      </li>
      <li class="nav-link">
        <i class='bx bx-calendar-event' ></i>
        <span class="mx-2"><a href="{% url 'CustomUser:event_list' %}" {% if event %} class="text-decoration-underline"  {% endif %}>Event</a></span>
      </li>
      <li class="nav-link">
        <i class='bx bxs-tree' ></i>
        <span class="mx-2"><a href="{% url 'CustomUser:tree_view' %}" {% if tree %} class="text-decoration-underline"  {% endif %}>Tree Plantation</a></span>
      </li>
      <li class="nav-link">
        <i class='bx bxs-report' ></i>
        <span class="mx-2"><a href="{% url 'CustomUser:report' %}" {% if report %} class="text-decoration-underline"  {% endif %}>Report</a></span>
      </li>
    </hr>
    <li class="nav-link">
    <i class='bx bx-download'></i>
      <span class="mx-2"><a href="{% url 'CustomUser:download' %}" {% if download %} class="text-decoration-underline"  {% endif %}>Download csv</a></span>
    </li>
    <li class="nav-link">
      <i class='bx bxs-book-reader'></i>
      <span class="mx-2"><a href="{% url 'CustomUser:profiling' %}">Analysis</a></span>
    </li>
    <li class="nav-link">
      <i class='bx bxs-log-out'></i>
      <span class="mx-2"><a href="{% url 'CustomUser:logout_user' %}" {% if download %} class="text-decoration-underline"  {% endif %}>logout</a></span>
    </li>

    </ul>

    <span href="#" class="nav-link h4 w-100 mb-5">
    </span>
  </div>

  <div class="p-1 my-container active-cont">
    <nav class="navbar top-navbar navbar-light bg-light px-5">
      <a class="btn border-0" id="menu-btn"><i class="bx bx-menu"></i></a>
    </nav>
    {% block content %}{% endblock %}
  </div>
  {% block script %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  <script src="{% static 'dashboard/script.js' %}"></script>
</body>

</html>

backend/CustomUser/templates/CustomUser/dashboard.html
{% extends "CustomUser/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="container">
    <div class="row mb-4">
        <div class="col-12 col-md-6 mt-3 mb-2">
            <div class="card" style="background-color:#defee2;">
                <div class="card-content">
                    <div class="card-body p-2">
                        <div class="d-flex">
                            <div class="align-self-center">
                                <i class="icon-pencil primary font-large-2 float-left"></i>
                            </div>
                            <div class="text-right">
                                <p>Admin Dashboard</p>
                                <h4 class="text-uppercase">Welcome {{user.get_full_name}}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-3 col-sm-6 col-12 mb-2">
            <div class="card h-100" style="background-color:#defee2;">
                <div class="card-content">
                    <div class="card-body p-2">
                        <div class="d-flex justify-content-between">
                            <div class="align-self-center">
                                <i class='bx bx-user' style="font-size: 4rem;"></i>
                            </div>
                            <div class="text-right">
                                <p>Total User</p>
                                <span>{{userreg}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 col-12 mb-2">
            <div class="card h-100" style="background-color:#defee2;">
                <div class="card-content">
                    <div class="card-body p-2">
                        <div class="d-flex justify-content-between">
                            <div class="align-self-center">
                                <i class='bx bx-user-voice' style="font-size: 4rem;"></i>
                            </div>
                            <div class="text-right">
                                <p>Complain</p>
                                <span>Solved:{{complain_solved}} Unsolved:{{complain_unsolved}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 col-12 mb-2">
            <div class="card h-100" style="background-color:#defee2;">
                <div class="card-content">
                    <div class="card-body p-2">
                        <div class="d-flex justify-content-between">
                            <div class="align-self-center">
                                <i class='bx bx-calendar-event' style="font-size: 4rem;"></i>
                            </div>
                            <div class="text-right">
                                <p>Event</p>
                                <span>Previous:{{event_previous}} Upcoming:{{event_upcoming}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 col-12 mb-2">
            <div class="card h-100" style="background-color:#defee2;">
                <div class="card-content">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <div class="align-self-center">
                                <i class='bx bxs-tree' style="font-size: 4rem;"></i>
                            </div>
                            <div class="text-right">
                                <p>Tree Planted</p>
                                <span>Count:{{tree_count}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h3 class="mt-2">Menu</h3>
    <div class="row">
        <div class="col-xl-2 col-sm-4 col-md-3 mb-2">
            <div class="text-center px-1 py-3" style="background-color:#defee2;">
                <i class='bx bx-user' style="font-size: 4rem;"></i>
                <a href="/admin">
                    <p style="color:black;">Admin</p>
                </div>
            </a>
        </div>
        <div class="col-xl-2 col-sm-4 col-md-3 mb-2">
            <div class="text-center px-1 py-3" style="background-color:#defee2;">
                <i class='bx bx-map-pin' style="font-size: 4rem;"></i>
                <a href="{% url 'CustomUser:map_view' %}">
                    <p style="color:black;">Map</p>
                </div>
            </a>
        </div>
        <div class="col-xl-2 col-sm-4 col-md-3 mb-2">
            <div class="text-center px-1 py-3" style="background-color:#defee2;">
                <i class='bx bxs-tree' style="font-size: 4rem;"></i>
                <a href="{% url 'CustomUser:tree_view' %}">
                    <p style="color:black;">Tree Planted</p>
                </div>
            </a>
        </div>
        <div class="col-xl-2 col-sm-4 col-md-3 mb-2">
            <div class="text-center px-1 py-3" style="background-color:#defee2;">
                <i class='bx bxs-calendar-event' style="font-size: 4rem;"></i>
                <a href="{% url 'CustomUser:event_list' %}">
                    <p style="color:black;">Event</p>
                </div>
            </a>
        </div>
        <div class="col-xl-2 col-sm-4 col-md-3 mb-2">
            <div class="text-center px-1 py-3" style="background-color:#defee2;">
                <i class='bx bxs-donate-heart' style="font-size: 4rem;"></i>
                <a href="{% url 'CustomUser:donate_list' %}">
                    <p style="color:black;">Donation</p>
                </div>
            </a>
        </div>
    </div>
    <div class="row my-3">
        <div class="col-xl-6 col-sm-12 col-md-8">
            <div class="card" style="background-color:#defee2;">
                <div class="card-content">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="align-self-center">
                                <i class="icon-pencil primary font-large-2 float-left"></i>
                            </div>
                            <div class="text-right">
                                <p>Generate report</p>
                                <h4 class="text-uppercase">Creating Report from User Complains</h4>
                            </div>
                        </div>
                        <div>
                            <a href="{% url 'CustomUser:report' %}" class="text-dark">Create report</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backend/CustomUser/templates/CustomUser/donation_pending_list.html
{% extends "CustomUser/base.html" %}
{% block title %}Donation{% endblock %}
{% block head %}
<style>
  li>.nav-link:hover{
    background-color: white;
  }
</style>
{% endblock %}
{% block content %}
<h4 class="text-dark p-3">Donation</h4>
<div class="d-flex flex-column">
  <div class="d-flex align-items-center justify-content-center">
    <div class="col-sm-8 col-lg-6 col-md-6 col-10">
      <div>
        <div class="card-body">
          <p class="m-0">Welcome to</p>
          <h5 style="color: #5EBC67;">WasteWatch Nepal Donation</h5>
          <ul class="list-group mt-3" >
            {% if donations %}
              {% for donation in donations %}
                <li class="list-group-item p-3">
                  <a class="nav-link" href="{% url 'CustomUser:make_donation' donation.id %}" style="color:black;" >{{donation.user.get_full_name}} donation <span class="btn-danger rounded-pill p-1">pending</span></a>
                </li>
              {% endfor %}
            {% else %}
            <li class="list-group-item p-3">
              No donation pending
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/CustomUser/templates/CustomUser/make_donation.html
{% extends "CustomUser/base.html" %}
{% block title %}Make Donation{% endblock %}
{% block content %}
<div class="d-flex flex-column justify-content-between">
    <nav class="navbar navbar-expand-lg">
        <div class="mx-lg-4 mx-3">
            <a href="{% url 'CustomUser:donate_list' %}" class="navbar-brand" style="color: #5EBC67;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
              </svg> <span class="fs-6">Back to Donation</span></a>
        </div>
    </nav>
    <div class="d-flex align-items-center justify-content-center">
        <div class="col-sm-8 col-lg-3 col-md-6 col-10">
            <div>
                <div class="card-body">
                    <p class="m-0">Add Tree Location</p>
                    <h5 style="color: #5EBC67;">WasteWatch Nepal</h5>
                    <form method="post" action="{% url 'CustomUser:make_donation' id %}">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Add" class="btn w-100" style="background-color: #5EBC67;color:#FFFFFF;">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}